access.h
void* vector_at(vector_t vector, size_t i, size_t z)
Return a pointer to the element in the vector at index i.
Though this operation doesn't have the _z suffix, it is a part of the explicit interface and takes the element size of the vector as z. This operation is redundant if the element type of the vector is known at compile time as it's identical to vector + i. This operation is implemented as a macro but documented as a function to clarify its intended usage. If i is the length of the vector then this will return a pointer to just past the last element of the vector. This operation is const qualified on the vector. That is if the element type of the vector is const qualified (vector is compatible with a vector_c), this will return a const void *. Otherwise this will return a void *. This is the inverse of vector_index() such that: vector_index(vector,vector_at(i))==i vector_at(vector,vector_index(elmt))==elmt If i is neither an index in the vector or its length then the behavior is undefined. vector_index() - the inverse operation to get the index of an element in a vector
Referenced by vector_debug_z, vector_eq_with_z, vector_excise_z, vector_find_last_z, vector_find_next_z, vector_get, vector_inject_z, vector_set, vector_swap_z, vector_tail_z.
void* vector_tail(vector_t vector)
Return a pointer to the last element in the vector.
This operation is implemented as a macro but documented as a function to clarify its intended usage. This operation is const qualified on the vector. That is if the element type of the vector is const qualified (vector is compatible with a vector_c) then this will return a const void *. Otherwise this will return a void *. If no last element is in the vector (the vector's length is zero) then the behavior is undefined. vector_tail_z() - the explicit interface analogue No vector_head() or vector_head_z() is available; a pointer to the first element in some vector is just vector.
References vector_tail_z.
void* vector_tail_z(vector_t vector, size_t z)
Return a pointer to the last element in the vector.
This operation is implemented as a macro but documented as a function to clarify its intended usage. This operation is const qualified on the vector. That is if the element type of the vector is const qualified (vector is compatible with a vector_c) then this will return a const void *. Otherwise this will return a void *. If no last element is in the vector (the vector's length is zero) then the behavior is undefined. vector_tail() - the implicit interface analogue No vector_head() or vector_head_z() is available; a pointer to the first element in some vector is just vector.
References vector_at, vector_length.
Referenced by vector_tail.
size_t vector_index(vector_c vector, const void *elmt, size_t z)
Return the index of the element at elmt in the vector.
Though this operation doesn't have the _z suffix, it is a part of the explicit interface and takes the element size of the vector as z. This operation is redundant if the element type of the vector is known at compile time as it's identical to elmt - vector. This doesn't inspect the data at elmt or the elements in the vector; elmt must already be a pointer to an element in the vector. This is the inverse of vector_at() such that: vector_at(vector,vector_index(elmt))==elmt vector_index(vector,vector_at(i))==i If elmt is NULL or isn't a pointer to an element in the vector then the behavior is undefined. If elmt is a pointer to an offset in an element in the vector then the behavior is undefined. vector_at() - the inverse operation to get a pointer to an element in a vector
void vector_get(vector_c vector, size_t i, void *elmt, size_t z)
Copy the element at index i in the vector into elmt.
Though this operation doesn't have the _z suffix, it is a part of the explicit interface and takes the element size of the vector as z. This operation is redundant if the element type of the vector is known at compile time as it's identical to *elmt = vector[i]. If i isn't an index in the vector or elmt is NULL then the behavior is undefined. vector the vector to operate on i the index of the element in the vector to copy from elmt the location to copy the element to z the element size of the vector vector_set() - the inverse operation to copy data into a vector
References vector_at.
Referenced by vector_pull_z, vector_shift_z.
void vector_set(vector_t vector, size_t i, const void *elmt, size_t z)
Copy the object at elmt into the vector at index i.
Though this operation doesn't have the _z suffix, it is a part of the explicit interface and takes the element size of the vector as z. This operation is redundant if the element type of the vector is known at compile time as it's identical to vector[i] = *elmt. If i isn't an index in the vector, elmt is NULL, or the type of the object at elmt is incompatible with the element type of the vector, then the behavior is undefined. vector the vector to operate on i the index of the element in the vector to copy to elmt the location to copy the element from z the element size of the vector vector_get() - the inverse operation to copy data from a vector
References vector_at.