common.h
typedef void* vector_t
Used to indicate a vector with an indeterminate element type.
This is intended to be used strictly when the element type of a vector is indeterminate (such as when implementing this file) and shouldn't be used otherwise. Instead a normal C pointer should be used. For example a vector with element type size_t should be declared and created with: size_t*v_size=vector_create();
typedef void const* vector_c
A vector_t with a const element type.
size_t vector_volume(vector_c vector)
Return the volume of the vector.
A vector's volume is the number of elements that it can hold without a reallocation and should always be greater than or equal to the vector's length.
Referenced by vector_duplicate_z, vector_ensure_z, vector_excise_z.
size_t vector_length(vector_c vector)
Return the length of (the number of elements in) the vector.
Referenced by vector_tail_z, vector_eq_with_z, vector_debug_z, vector_inject_z, vector_append_z, vector_extend_z, vector_excise_z, vector_truncate_z, vector_shrink_z, vector_find_next_z, vector_pull_z, vector_sort_z, vector_duplicate_z.