comparison.h
_Bool vector_eq(vector_c va, vector_c vb, _Bool(*eq)(const void *a, const void *b))
Return whether vector va is equivalent to vector vb.
Here "equivalent" means that both of va and vb are NULL, or neither va or vb is NULL and: va and vb have the same length, and eq returns true when called on each element in va and the element at the same index in vb va a vector to operate on vb a vector to operate on eq the equality function that will be used to decide whether an element in va is equivalent to an element in vb whether vector va is equivalent to vector vb
References vector_eq_z.
_Bool vector_eq_z(vector_c va, vector_c vb, _Bool(*eq)(const void *a, const void *b), size_t za, size_t zb)
Return whether vector va is equivalent to vector vb.
Here "equivalent" means that both of va and vb are NULL, or neither va or vb is NULL and: va and vb have the same length, and eq returns true when called on each element in va and the element at the same index in vb va a vector to operate on vb a vector to operate on eq the equality function that will be used to decide whether an element in va is equivalent to an element in vb za the element size of va zb the element size of vb whether vector va is equivalent to vector vb
References vector_eq_with_z.
Referenced by vector_eq.
_Bool vector_eq_with(vector_c va, vector_c vb, _Bool(*eq)(const void *a, const void *b, void *data), void *data)
Return whether vector va is equivalent to vector vb with contextual information.
Here "equivalent" means that both of va and vb are NULL, or neither va or vb is NULL and: va and vb have the same length, and eq returns true when called on each element in va and the element at the same index in vb va a vector to operate on vb a vector to operate on eq the equality function that will be used to decide whether an element in va is equivalent to an element in vb data contextual information to pass as the last argument to eq whether vector va is equivalent to vector vb
References vector_eq_with_z.
_Bool vector_eq_with_z(vector_c va, vector_c vb, _Bool(*eq)(const void *a, const void *b, void *data), void *data, size_t za, size_t zb)
Return whether vector va is equivalent to vector vb with contextual information.
Here "equivalent" means that both of va and vb are NULL, or neither va or vb is NULL and: va and vb have the same length, and eq returns true when called on each element in va and the element at the same index in vb va a vector to operate on vb a vector to operate on eq the equality function that will be used to decide whether an element in va is equivalent to an element in vb data contextual information to pass as the last argument to eq za the element size of va zb the element size of vb whether vector va is equivalent to vector vb
References vector_at, vector_length.
Referenced by vector_eq_with, vector_eq_z.
int vector_cmp(vector_c va, vector_c vb, int(*cmp)(const void *a, const void *b))
int vector_cmp_z(vector_c va, vector_c vb, int(*cmp)(const void *a, const void *b), size_t za, size_t zb)
int vector_cmp_with(vector_c va, vector_c vb, int(*cmp)(const void *a, const void *b, void *data), void *data)
int vector_cmp_with_z(vector_c va, vector_c vb, int(*cmp)(const void *a, const void *b, void *data), void *data, size_t za, size_t zb)