vector_module
_Bool vector_eq(vector_c va, vector_c vb, _Bool(*eq)(const void *a, const void *b))
Return whether vector va is equivalent to vector vb.
Here "equivalent" means that both of va and vb are NULL, or neither va or vb is NULL and: va and vb have the same length, and eq returns true when called on each element in va and the element at the same index in vb va a vector to operate on vb a vector to operate on eq the equality function that will be used to decide whether an element in va is equivalent to an element in vb whether vector va is equivalent to vector vb
References vector_eq_z.
_Bool vector_eq_z(vector_c va, vector_c vb, _Bool(*eq)(const void *a, const void *b), size_t za, size_t zb)
Return whether vector va is equivalent to vector vb.
Here "equivalent" means that both of va and vb are NULL, or neither va or vb is NULL and: va and vb have the same length, and eq returns true when called on each element in va and the element at the same index in vb va a vector to operate on vb a vector to operate on eq the equality function that will be used to decide whether an element in va is equivalent to an element in vb za the element size of va zb the element size of vb whether vector va is equivalent to vector vb
References vector_eq_with_z.
Referenced by vector_eq.
_Bool vector_eq_with(vector_c va, vector_c vb, _Bool(*eq)(const void *a, const void *b, void *data), void *data)
Return whether vector va is equivalent to vector vb with contextual information.
Here "equivalent" means that both of va and vb are NULL, or neither va or vb is NULL and: va and vb have the same length, and eq returns true when called on each element in va and the element at the same index in vb va a vector to operate on vb a vector to operate on eq the equality function that will be used to decide whether an element in va is equivalent to an element in vb data contextual information to pass as the last argument to eq whether vector va is equivalent to vector vb
References vector_eq_with_z.
_Bool vector_eq_with_z(vector_c va, vector_c vb, _Bool(*eq)(const void *a, const void *b, void *data), void *data, size_t za, size_t zb)
Return whether vector va is equivalent to vector vb with contextual information.
Here "equivalent" means that both of va and vb are NULL, or neither va or vb is NULL and: va and vb have the same length, and eq returns true when called on each element in va and the element at the same index in vb va a vector to operate on vb a vector to operate on eq the equality function that will be used to decide whether an element in va is equivalent to an element in vb data contextual information to pass as the last argument to eq za the element size of va zb the element size of vb whether vector va is equivalent to vector vb
References vector_at, vector_length.
Referenced by vector_eq_with, vector_eq_z.
int vector_cmp(vector_c va, vector_c vb, int(*cmp)(const void *a, const void *b))
int vector_cmp_z(vector_c va, vector_c vb, int(*cmp)(const void *a, const void *b), size_t za, size_t zb)
int vector_cmp_with(vector_c va, vector_c vb, int(*cmp)(const void *a, const void *b, void *data), void *data)
int vector_cmp_with_z(vector_c va, vector_c vb, int(*cmp)(const void *a, const void *b, void *data), void *data, size_t za, size_t zb)
size_t vector_find(vector_c vector, bool(*eqf)(const void *elmt, const void *data), const void *data)
Find the first element in the vector equal to data.
This will return the index of the first element in the vector for which the expression eqf(elmt, data) is true where elmt is the location of an element in the vector. If no such element is in the vector then this will return SIZE_MAX. Note that the largest possible index into an array of any type is SIZE_MAX - 1 so SIZE_MAX is an unambiguous indication that no such element is in the vector. vector the vector to operate on eqf the function to use to determine equality data additional data to pass to eqf the index of the element on success; otherwise SIZE_MAX
References vector_find_z.
size_t vector_find_z(vector_c vector, bool(*eqf)(const void *elmt, const void *data), const void *data, size_t z)
Find the first element in the vector equal to data.
This will return the index of the first element in the vector for which the expression eqf(elmt, data) is true where elmt is the location of an element in the vector. If no such element is in the vector then this will return SIZE_MAX. Note that the largest possible index into an array of any type is SIZE_MAX - 1 so SIZE_MAX is an unambiguous indication that no such element is in the vector. vector the vector to operate on eqf the function to use to determine equality data additional data to pass to eqf z the element size of the vector the index of the element on success; otherwise SIZE_MAX
References vector_find_next_z.
Referenced by vector_find.
size_t vector_find_next(vector_c vector, size_t i, bool(*eqf)(const void *elmt, const void *data), const void *data)
Find the first element at or after index i in the vector equal to data.
This will return the index of the first element in the vector at or after index i for which the expression eqf(elmt, data) is true where elmt is the location of an element in the vector. Index i is inclusive so if the element at that index is equal to data, then i itself will be returned. To iterate through all elements in the vector equal to data do: size_ti=vector_find(vector,eqf,data); while(i<vector_length(vector)){ ... i=vector_find_next(vector,i+1,eqf,data); } If no such element is in the vector at or after index i, then this will return SIZE_MAX. Note that the largest possible index into an array of any type is SIZE_MAX - 1 so SIZE_MAX is an unambiguous indication that no such element is in the vector. If i is neither an index in the vector or its length then the behavior is undefined. As a special case if i is the vector's length, then will return SIZE_MAX. vector the vector to operate on i the lowest index in the vector to consider eqf the function to use to determine equality data additional data to pass to eqf the index of the element on success; otherwise SIZE_MAX
References vector_find_next_z.
size_t vector_find_next_z(vector_c vector, size_t i, bool(*eqf)(const void *elmt, const void *data), const void *data, size_t z)
Find the first element at or after index i in the vector equal to data.
This will return the index of the first element in the vector at or after index i for which the expression eqf(elmt, data) is true where elmt is the location of an element in the vector. Index i is inclusive so if the element at that index is equal to data, then i itself will be returned. To iterate through all elements in the vector equal to data do: size_ti=vector_find_z(vector,eqf,data,z); while(i<vector_length(vector)){ ... i=vector_find_next_z(vector,i+1,eqf,data,z); } If no such element is in the vector at or after index i, then this will return SIZE_MAX. Note that the largest possible index into an array of any type is SIZE_MAX - 1 so SIZE_MAX is an unambiguous indication that no such element is in the vector. If i is neither an index in the vector or its length then the behavior is undefined. As a special case if i is the vector's length, then will return SIZE_MAX. vector the vector to operate on i the lowest index in the vector to consider eqf the function to use to determine equality data additional data to pass to eqf z the element size of the vector the index of the element on success; otherwise SIZE_MAX
References vector_at, vector_length.
Referenced by vector_find_next, vector_find_z.
size_t vector_find_last(vector_c vector, size_t i, bool(*eqf)(const void *elmt, const void *data), const void *data)
Find the last element before index i in the vector equal to data.
This will return the index of the last element in the vector before index i for which the expression eqf(elmt, data) is true where elmt is the location of an element in the vector. Index i is exclusive so this will never return i itself. To iterate in reverse order through all elements in the vector equal to data do: size_ti=vector_find_last(vector,vector_length(vector),eqf,data); while(i<SIZE_MAX){ ... i=vector_find_last(vector,i,eqf,data); } If no such element is in the vector before index i, then this will return SIZE_MAX. Note that the largest possible index into an array of any type is SIZE_MAX - 1 so SIZE_MAX is an unambiguous indication that no such element is in the vector. If i is neither an index in the vector or its length then the behavior is undefined. vector the vector to operate on i the index in or just after the vector to search before eqf the function to use to determine equality data additional data to pass to eqf the index of the element on success; otherwise SIZE_MAX
References vector_find_last_z.
size_t vector_find_last_z(vector_c vector, size_t i, bool(*eqf)(const void *elmt, const void *data), const void *data, size_t z)
Find the last element before index i in the vector equal to data.
This will return the index of the last element in the vector before index i for which the expression eqf(elmt, data) is true where elmt is the location of an element in the vector. Index i is exclusive so this will never return i itself. To iterate in reverse order through all elements in the vector equal to data do: size_ti=vector_find_last_z(vector,vector_length(vector),eqf,data,z); while(i<SIZE_MAX){ ... i=vector_find_last_z(vector,i,eqf,data,z); } If no such element is in the vector before index i, then this will return SIZE_MAX. Note that the largest possible index into an array of any type is SIZE_MAX - 1 so SIZE_MAX is an unambiguous indication that no such element is in the vector. If i is neither an index in the vector or its length then the behavior is undefined. vector the vector to operate on i the index in or just after the vector to search before eqf the function to use to determine equality data additional data to pass to eqf z the element size of the vector the index of the element on success; otherwise SIZE_MAX
References vector_at.
Referenced by vector_find_last.
size_t vector_search(vector_c vector, const void *elmt, int(*cmpf)(const void *a, const void *b))
Find the first element in the sorted vector equal to elmt.
The vector must be partitioned with respect to elmt according to cmpf. That is, all the elements that compare less than must appear before all the elements that compare equal to, and those must appear before all the elements that compare greater than elmt according to cmpf. A vector sorted by a previous call to vector_sort() with the same cmpf satisfies these requirements. The behavior is undefined if the vector is not already partitioned with respect to elmt in ascending order according to cmpf. vector the vector to operate on elmt the element to search for cmpf the function to use to determine equality the index of the element on success; otherwise SIZE_MAX vector_search_z() The equivalent operation in the explicit interface
size_t vector_search_z(vector_c vector, const void *elmt, int(*cmpf)(const void *a, const void *b), size_t z)
void vector_sort(vector_t vector, int(*cmp)(const void *a, const void *b))
Sort the vector in ascending order on a comparator.
This isn't a stable sort: if cmp indicates that two elements are equal, their relative order in the result is unspecified. vector the vector to operate on cmp The comparator that will be called to establish the relative order of two elements. This should return a negative integer if a is less than (should come before) b, a positive integer if a is greater than (should come after) b, and zero if a and b are equal. It must return consistent results when called for the same elements, regardless of their indices in the vector. This function must encode a strict total order of the elements in the vector. That is, for any elements a, b, and c: $a = a$ If $a = b$ and $b = c$ then $a = c$ If $a < b$ then $b > a$ If $a < b$ and $b < c$ then $a < c$
References vector_sort_z.
void vector_sort_z(vector_t vector, int(*cmp)(const void *a, const void *b), size_t z)
Sort the vector in ascending order on a comparator.
This isn't a stable sort: if cmp indicates that two elements are equal, their relative order in the result is unspecified. vector the vector to operate on cmp The comparator that will be called to establish the relative order of two elements. This should return a negative integer if a is less than (should come before) b, a positive integer if a is greater than (should come after) b, and zero if a and b are equal. It must return consistent results when called for the same elements, regardless of their indices in the vector. This function must encode a strict total order of the elements in the vector. That is, for any elements a, b, and c: $a = a$ If $a = b$ and $b = c$ then $a = c$ If $a < b$ then $b > a$ If $a < b$ and $b < c$ then $a < c$ z the element size of the vector
References vector_length.
Referenced by vector_sort.
void vector_sort_with(vector_t vector, int(*cmp)(const void *a, const void *b, void *data), void *data)
Sort the vector in ascending order on a contextual comparator.
This isn't a stable sort: if cmp indicates that two elements are equal, their relative order in the result is unspecified. vector the vector to operate on cmp The comparator that will be called to establish the relative order of two elements. This should return a negative integer if a is less than (should come before) b, a positive integer if a is greater than (should come after) b, and zero if a and b are equal. It must return consistent results when called for the same elements, regardless of their indices in the vector. This function must encode a strict total order of the elements in the vector. That is, for any elements a, b, and c: $a = a$ If $a = b$ and $b = c$ then $a = c$ If $a < b$ then $b > a$ If $a < b$ and $b < c$ then $a < c$ data contextual information to pass as the last argument to cmp
References vector_sort_with_z.
void vector_sort_with_z(vector_t vector, int(*cmp)(const void *a, const void *b, void *data), void *data, size_t z)
Sort the vector in ascending order on a contextual comparator.
This isn't a stable sort: if cmp indicates that two elements are equal, their relative order in the result is unspecified. vector the vector to operate on cmp The comparator that will be called to establish the relative order of two elements. This should return a negative integer if a is less than (should come before) b, a positive integer if a is greater than (should come after) b, and zero if a and b are equal. It must return consistent results when called for the same elements, regardless of their indices in the vector. This function must encode a strict total order of the elements in the vector. That is, for any elements a, b, and c: $a = a$ If $a = b$ and $b = c$ then $a = c$ If $a < b$ then $b > a$ If $a < b$ and $b < c$ then $a < c$ data contextual information to pass as the last argument to cmp z the element size of the vector
Referenced by vector_sort_with.