insert.h
vector_t vector_insert(restrict vector_t vector, size_t i, const void *restrict elmt)
Insert the data at elmt into the vector at index i.
The index of the inserted element will be i. If i is the length of the vector then this will append the element to the vector. If elmt is NULL then the inserted element will be uninitialized. If the resultant length of the vector would overflow a size_t then this will set errno to ENOMEM and return NULL. Otherwise this will call vector_ensure(). If that fails then the vector will be unmodified and the value of errno set by realloc() will be retained. If i is neither an index in the vector or its length then the behavior is undefined. If elmt isn't NULL and its type is incompatible with the element type of the vector then the behavior is undefined. If elmt is a location in the vector itself then the behavior is undefined. vector the vector to operate on i the index in the vector to insert the element elmt the location of the element to insert the resultant vector on success; otherwise NULL vector_insert_z() - the explicit interface analogue
References vector_insert_z.
vector_t vector_insert_z(restrict vector_t vector, size_t i, const void *restrict elmt, size_t z)
Insert the data at elmt into the vector at index i.
The index of the inserted element will be i. If i is the length of the vector then this will append the element to the vector. If elmt is NULL then the inserted element will be uninitialized. If the resultant length of the vector would overflow a size_t then this will set errno to ENOMEM and return NULL. Otherwise this will call vector_ensure_z(). If that fails then the vector will be unmodified and the value of errno set by realloc() will be retained. If i is neither an index in the vector or its length then the behavior is undefined. If elmt isn't NULL and its type is incompatible with the element type of the vector then the behavior is undefined. If elmt is a location in the vector itself then the behavior is undefined. vector the vector to operate on i the index in the vector to insert the element elmt the location of the element to insert z the element size of the vector the resultant vector on success; otherwise NULL vector_insert() - the implicit interface analogue
References vector_inject_z.
Referenced by vector_insert.
vector_t vector_inject(restrict vector_t vector, size_t i, const void *restrict elmt, size_t n)
Insert n elements from elmt into the vector starting at index i.
The index of the first inserted element will be i. If i is the length of the vector then this will append the elements to the vector. If elmt is NULL then the inserted elements will be uninitialized. This is more efficient than calling vector_insert() n times as the elements after i + n will be shifted only once. If the resultant length of the vector would overflow a size_t then this will set errno to ENOMEM and return NULL. Otherwise this will call vector_ensure(). If that fails then the vector will be unmodified and the value of errno set by realloc() will be retained. If i is neither an index in the vector or its length then the behavior is undefined. If elmt isn't NULL and its type is incompatible with the element type of the vector then the behavior is undefined. If elmt is a location in the vector itself then the behavior is undefined. vector the vector to operate on i the index in the vector to insert the elements elmt the location of the elements to insert n the number of elements to insert from elmt the resultant vector on success; otherwise NULL vector_inject_z() - the explicit interface analogue
References vector_inject_z.
vector_t vector_inject_z(restrict vector_t vector, size_t i, const void *restrict elmt, size_t n, size_t z)
Insert n elements from elmt into the vector starting at index i.
The index of the first inserted element will be i. If i is the length of the vector then this will append the elements to the vector. If elmt is NULL then the inserted elements will be uninitialized. This is more efficient than calling vector_insert_z() n times as the elements after i + n will be shifted only once. If the resultant length of the vector would overflow a size_t then this will set errno to ENOMEM and return NULL. Otherwise this will call vector_ensure_z(). If that fails then the vector will be unmodified and the value of errno set by realloc() will be retained. If i is neither an index in the vector or its length then the behavior is undefined. If elmt isn't NULL and its type is incompatible with the element type of the vector then the behavior is undefined. If elmt is a location in the vector itself then the behavior is undefined. vector the vector to operate on i the index in the vector to insert the elements elmt the location of the elements to insert n the number of elements to insert from elmt z the element size of the vector the resultant vector on success; otherwise NULL vector_inject() - the implicit interface analogue
References vector_at, vector_ensure_z, vector_length.
Referenced by vector_append_z, vector_extend_z, vector_inject, vector_insert_z.
vector_t vector_append(restrict vector_t vector, const void *restrict elmt)
Insert the data at elmt as the last element in the vector.
If elmt is NULL then the inserted element will be uninitialized. If the resultant length of the vector would overflow a size_t then this will set errno to ENOMEM and return NULL. Otherwise this will call vector_ensure(). If that fails then the vector will be unmodified and the value of errno set by realloc() will be retained. If elmt isn't NULL and its type is incompatible with the element type of the vector then the behavior is undefined. If elmt is a location in the vector itself then the behavior is undefined. vector the vector to operate on elmt the location of the element to append the resultant vector on success; otherwise NULL vector_append_z() - the explicit interface analogue
References vector_append_z.
vector_t vector_append_z(restrict vector_t vector, const void *restrict elmt, size_t z)
Insert the data at elmt as the last element in the vector.
If elmt is NULL then the inserted element will be uninitialized. If the resultant length of the vector would overflow a size_t then this will set errno to ENOMEM and return NULL. Otherwise this will call vector_ensure_z(). If that fails then the vector will be unmodified and the value of errno set by realloc() will be retained. If elmt isn't NULL and its type is incompatible with the element type of the vector then the behavior is undefined. If elmt is a location in the vector itself then the behavior is undefined. vector the vector to operate on elmt the location of the element to append z the element size of the vector the resultant vector on success; otherwise NULL vector_append_z() - the explicit interface analogue
References vector_inject_z, vector_length.
Referenced by vector_append.
vector_t vector_extend(restrict vector_t vector, const void *restrict elmt, size_t n)
Append n elements from elmt to the tail of the vector.
If elmt is NULL then the inserted elements will be uninitialized. If the resultant length of the vector would overflow a size_t then this will set errno to ENOMEM and return NULL. Otherwise this will call vector_ensure(). If that fails then the vector will be unmodified and the value of errno set by realloc() will be retained. If elmt isn't NULL and its type is incompatible with the element type of the vector then the behavior is undefined. If elmt is a location in the vector itself then the behavior is undefined. vector the vector to operate on elmt the location of the elements to insert n the number of elements to insert from elmt the resultant vector on success; otherwise NULL vector_extend_z() - the explicit interface analogue
References vector_extend_z.
vector_t vector_extend_z(restrict vector_t vector, const void *restrict elmt, size_t n, size_t z)
Append n elements from elmt to the tail of the vector.
If elmt is NULL then the inserted elements will be uninitialized. If the resultant length of the vector would overflow a size_t then this will set errno to ENOMEM and return NULL. Otherwise this will call vector_ensure_z(). If that fails then the vector will be unmodified and the value of errno set by realloc() will be retained. If elmt isn't NULL and its type is incompatible with the element type of the vector then the behavior is undefined. If elmt is a location in the vector itself then the behavior is undefined. vector the vector to operate on elmt the location of the elements to insert n the number of elements to insert from elmt z the element size of the vector the resultant vector on success; otherwise NULL vector_extend_z() - the explicit interface analogue
References vector_inject_z, vector_length.
Referenced by vector_extend.