move.h
void vector_swap(vector_t vector, size_t i, size_t j)
Swap the element at index i with the element at index j in the vector.
Though this is implemented as a macro it's documented as a function to clarify its intended usage. If either i or j isn't an index in the vector then the behavior of this operation is undefined. vector the vector to operate on i the index of an element in the vector to swap j the index of an element in the vector to swap vector_swap_z() - The explicit interface analogue
References vector_swap_z.
void vector_swap_z(vector_t vector, size_t i, size_t j, size_t z)
Swap the element at index i with the element at index j in the vector.
If either i or j isn't an index in the vector then the behavior of this operation is undefined. vector the vector to operate on i the index of an element in the vector to swap j the index of an element in the vector to swap z the element size of the vector vector_swap() - The implicit interface analogue
References vector_at.
Referenced by vector_move_z, vector_swap.
void vector_move(vector_t vector, size_t target, size_t source)
Move the element at index source to index target in the vector.
This will move the element at index source to be at index target, the element previously at index target to index target + 1, and so on. When complete the length of the vector is unchanged and (with the exception of the element at source) the relative order of each element in the vector is unchanged. For example: int*sample=vector_define(int,2,4,6,8,10,12); vector_move(sample,4,2); sample=={2,4,10,6,8,12}; If target or source isn't an index in the vector then the behavior is undefined. vector the vector to operate on target the index in the vector to move the element to source the index of the element in the vector to move vector_move_z() - The explicit interface analogue
References vector_move_z.
void vector_move_z(vector_t vector, size_t target, size_t source, size_t z)
Move the element at index source to index target in the vector.
This will move the element at index source to be at index target, the element previously at index target to index target + 1, and so on. When complete the length of the vector is unchanged and (with the exception of the element at source) the relative order of each element in the vector is unchanged. For example: int*sample=vector_define(int,2,4,6,8,10,12); vector_move(sample,4,2); sample=={2,4,10,6,8,12}; If target or source isn't an index in the vector then the behavior is undefined. vector the vector to operate on target the index in the vector to move the element to source the index of the element in the vector to move z the element size of the vector vector_move() - The implicit interface analogue
References vector_swap_z.
Referenced by vector_move.