remove.h
vector_t vector_remove(vector_t vector, size_t i)
Remove the element at index i from the vector.
All elements at indices greater than i are shifted one element toward the head of the vector. Once the element is removed and subsequent elements are shifted, if the length of the vector is reduced such that $ length \le \frac{1}{2}(volume - 1) $, a vector_resize() will be attempted to reduce the volume to: \[ volume = \frac{length \times 6 + 4}{5} \] On success the shrunk vector will be returned. Otherwise the vector will be returned as is (without the element). If i isn't an index in the vector then the behavior is undefined. vector the vector to operate on i the index in the vector of the element to remove the resultant vector
References vector_remove_z.
vector_t vector_remove_z(vector_t vector, size_t i, size_t z)
Remove the element at index i from the vector.
All elements at indices greater than i are shifted one element toward the head of the vector. Once the element is removed and subsequent elements are shifted, if the length of the vector is reduced such that $ length \le \frac{1}{2}(volume - 1) $, a vector_resize_z() will be attempted to reduce the volume to: \[ volume = \frac{length \times 6 + 4}{5} \] On success the shrunk vector will be returned. Otherwise the vector will be returned as is (without the element). If i isn't an index in the vector then the behavior is undefined. vector the vector to operate on i the index in the vector of the element to remove z the element size of the vector the resultant vector
References vector_excise_z.
Referenced by vector_pull_z, vector_remove, vector_shift_z.
vector_t vector_excise(vector_t vector, size_t i, size_t n)
Remove n elements at index i from the vector.
All elements at indices greater than i + n are shifted n elements toward the head of the vector. Once the elements are removed and subsequent elements are shifted, if the length of the vector is reduced such that $ length \le \frac{1}{2}(volume - 1) $, a vector_resize() will be attempted to reduce the volume to: \[ volume = \frac{length \times 6 + 4}{5} \] On success the shrunk vector will be returned. Otherwise the vector will be returned as is (without the elements). If i or any index from i to i + n inclusive isn't an index in the vector then the behavior is undefined. vector the vector to operate on i the index in the vector of the elements to remove n the number of elements to remove from the vector the resultant vector
References vector_excise_z.
vector_t vector_excise_z(vector_t vector, size_t i, size_t n, size_t z)
Remove n elements at index i from the vector.
All elements at indices greater than i + n are shifted n elements toward the head of the vector. Once the elements are removed and subsequent elements are shifted, if the length of the vector is reduced such that $ length \le \frac{1}{2}(volume - 1) $, a vector_resize_z() will be attempted to reduce the volume to: \[ volume = \frac{length \times 6 + 4}{5} \] On success the shrunk vector will be returned. Otherwise the vector will be returned as is (without the elements). If i or any index from i to i + n inclusive isn't an index in the vector then the behavior is undefined. vector the vector to operate on i the index in the vector of the elements to remove n the number of elements to remove from the vector z the element size of the vector the resultant vector
References vector_at, vector_length, vector_resize_z, vector_volume.
Referenced by vector_excise, vector_remove_z, vector_truncate_z.
vector_t vector_truncate(vector_t vector, size_t length)
Reduce the length of the vector to length.
This will remove elements from the tail of the vector until its length is length. The number of elements removed is the difference between length and the length of the vector. The resultant volume of the vector will follow the rule in vector_excise(). If length is greater than the length of the vector then the behavior is undefined. vector the vector to operate on length the length of the resultant vector the resultant vector
References vector_truncate_z.
vector_t vector_truncate_z(vector_t vector, size_t length, size_t z)
Reduce the length of the vector to length.
This will remove elements from the tail of the vector until its length is length. The number of elements removed is the difference between length and the length of the vector. The resultant volume of the vector will follow the rule in vector_excise_z(). If length is greater than the length of the vector then the behavior is undefined. vector the vector to operate on length the length of the resultant vector z the element size of the vector the resultant vector
References vector_excise_z, vector_length.
Referenced by vector_truncate.