resize.h
vector_t vector_resize(vector_t vector, size_t volume)
Resize the volume of the vector to volume.
If volume is less than the length of the vector then the vector will be truncated and have its length reduced to volume. This will fail if the underlying realloc() returns NULL. The C standard doesn't guarantee success of a realloc() to a smaller size, so this can fail even if volume is less than the volume of the vector. In either case if the realloc() fails then the vector will be unmodified and the value of errno set by realloc() will be retained. vector the vector to operate on volume the volume to resize the vector to the resized vector on success; otherwise NULL vector_resize_z() - the explicit interface analogue
References vector_resize_z.
vector_t vector_resize_z(vector_t vector, size_t volume, size_t z)
Resize the volume of the vector to volume.
If volume is less than the length of the vector then the vector will be truncated and have its length reduced to volume. This will fail if the underlying realloc() returns NULL. The C standard doesn't guarantee success of a realloc() to a smaller size, so this can fail even if volume is less than the volume of the vector. In either case if the realloc() fails then the vector will be unmodified and the value of errno set by realloc() will be retained. vector the vector to operate on volume the volume to resize the vector to z the element size of the vector the resized vector on success; otherwise NULL vector_resize() - the implicit interface analogue
Referenced by vector_ensure_z, vector_excise_z, vector_resize, vector_shrink_z.
vector_t vector_ensure(vector_t vector, size_t length)
Ensure that the volume of the vector is no less than length.
If the volume of the vector is less than length then vector_resize() will be called. Preallocation is attempted to accomodate future increases in length according to the formula: \[ volume = \frac{length \times 8 + 3}{5} \] If this preallocation fails then a resize to length will be attempted. If that also fails then the vector will be unmodified. On success, subsequent insertions (through vector_insert(), vector_append(), etc.) into the vector are guaranteed to be successful so long as the resultant length doesn't exceed length. Note that the vector doesn't remember this length. As a result calling any functions that can decrease the volume of the vector (like vector_resize(), vector_shrink(), vector_remove(), etc.) will invalidate this guarantee. vector the vector to operate on length the minimum length to accomodate in the vector the resultant vector on success; otherwise NULL
References vector_ensure_z.
vector_t vector_ensure_z(vector_t vector, size_t length, size_t z)
Ensure that the volume of the vector is at least length.
If the volume of the vector is less than length then vector_resize_z() will be called. Preallocation is attempted to accomodate future increases in length according to the formula: \[ volume = \frac{length \times 8 + 3}{5} \] If this preallocation fails then a resize to length will be attempted. If that also fails then the vector will be unmodified. On success, subsequent insertions (through vector_insert_z(), vector_append_z(), etc.) into the vector are guaranteed to be successful so long as the resultant length doesn't exceed length. Note that the vector doesn't remember this length. As a result calling any functions that can decrease the volume of the vector (like vector_resize_z(), vector_shrink_z(), vector_remove_z(), etc.) will invalidate this guarantee. vector the vector to operate on length the minimum length to accomodate in the vector z the element size of the vector the resultant vector on success; otherwise NULL
References vector_resize_z, vector_volume.
Referenced by vector_ensure, vector_inject_z.
vector_t vector_shrink(vector_t vector)
Reduce the volume of the vector to its length.
This is almost a vector_resize() to the vector's length. However if the resize fails then vector will be returned umodified and the value of errno set by realloc() will be retained. vector the vector to operate on the shrunk vector on success; otherwise the unmodified vector vector_shrink_z() - the explicit interface analogue
References vector_shrink_z.
vector_t vector_shrink_z(vector_t vector, size_t z)
Reduce the volume of the vector to its length.
This is almost a vector_resize_z() to the vector's length. However if the resize fails then the vector will be returned umodified and the value of errno set by realloc() will be retained. vector the vector to operate on z the element size of the vector the shrunk vector on success; otherwise the unmodified vector vector_shrink() - the implicit interface analogue
References vector_length, vector_resize_z.
Referenced by vector_shrink.