# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  clang-test:
    parameters:
      cc:
        description: The value of the CC environment variable
        type: string
        default: clang-7
    docker:
    - image: kaitingc/debian-test
    environment:
      CC: "<<parameters.cc>>"
    steps:
    - run: apt-get install "$CC"
    - checkout
    - run: cmake .
    - run: ctest --output-on-failure

  test:
    docker:
    - image: kaitingc/debian-test
    steps:
    - checkout
    - run: cmake .
    - run: ctest --output-on-failure

workflows:
  test:
    jobs:
    - clang-test:
        matrix:
          parameters:
            cc:
            - clang-7
            - clang-8
            - clang-9
