#! /bin/bash

cd ..

CMAKE_VERSION=3.18.4

wget -N "https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz"
sudo tar -C /usr/local -xzf "cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz" --strip-components=1
cmake . -DDOCUMENTATION=on
make documentation
